# Generated by Django 5.1.5 on 2025-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_collaboraterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboraterequest',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='recipeName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
