# Generated by Django 5.1.5 on 2025-02-05 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_message_collaboraterequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboraterequest',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='collaboration_image'),
        ),
    ]
