# Generated by Django 5.1.5 on 2025-02-05 21:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_collaboraterequest_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboraterequest',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='collaboration_image'),
        ),
    ]
