# Generated by Django 5.1.5 on 2025-02-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_chef_delete_chefprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='interests',
        ),
        migrations.AlterField(
            model_name='chef',
            name='profile_image',
            field=models.ImageField(upload_to='chefs/'),
        ),
    ]
