# Generated by Django 5.1.5 on 2025-02-06 00:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_remove_chef_interests_alter_chef_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
