# Generated by Django 5.1.5 on 2025-02-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_alter_chef_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='profile_image',
        ),
    ]
