# Generated by Django 5.1.5 on 2025-02-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_remove_chef_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
